excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

disabled_rules:
  - todo
  - line_length
  - empty_enum_arguments
  - trailing_whitespace
  - force_try # check later
    
analyzer_rules: # Rules run by `swiftlint analyze`
  - explicit_self

identifier_name:
  excluded: # excluded via string array
    - id
    - i
    - j
